# Generated by Django 4.2.7 on 2023-11-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('max_amount', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('interest_type', models.CharField(max_length=100)),
                ('max_repayment_period', models.IntegerField()),
                ('term_period', models.CharField(max_length=100)),
                ('late_payment_penalty', models.IntegerField()),
                ('loan_product_status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loan_product',
            },
        ),
    ]
