# Generated by Django 4.2.7 on 2023-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='interest_type',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='late_payment_penalty',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='loan_product_status',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='max_repayment_period',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='term_period',
        ),
    ]
