# Generated by Django 4.2.7 on 2023-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_products', '0002_remove_loanproduct_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='name',
        ),
    ]
