# Generated by Django 4.2.7 on 2023-11-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_products', '0003_remove_loanproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='product_description',
            field=models.TextField(),
        ),
    ]
